# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - |
        watchexec \
          -r \
          -w ~/.config/StartTree \
          -w {{ .USER_WORKING_DIR }}/config.yaml \
          -w {{ .USER_WORKING_DIR }}/generate.py \
          -w {{ .USER_WORKING_DIR }}/src \
          -w {{ .USER_WORKING_DIR }}/skeletons/index.html \
          -w {{ .USER_WORKING_DIR }}/skeletons/style.css \
          -i '*/skeletons/search.bundle.js' \
          -i '*/node_modules/*' \
          -i '*/.cache/*' \
          -- task run

  run:
    cmds:
      - |
        set -x
        ./init.sh
        npm run build
        source ./venv/bin/activate
        python3 ./generate.py
        npm run serve
    silent: true
